# name: Deploy
# on:
#   workflow_dispatch:
#   push:
#     branches: [main]
# jobs:
#   clean:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10
#     steps:
#     - uses: c-hive/gha-remove-artifacts@master
#       with:
#         age: '0 minutes'
#         skip-recent: 2 # keep 2 previous versions for n-1 rollback; one version gets discated in queue during deploy hence 2;
#   build:
#     runs-on: ubuntu-latest
#     needs: clean
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: refs/heads/main
#     - run: docker build --tag ${{ github.event.repository.name }} ${{ github.workspace }}
#     - run: docker save -o ${{ github.sha }}.tar ${{ github.event.repository.name }}
#     - uses: actions/upload-artifact@v3
#       with:
#         name: docker@${{ github.sha }}
#         path: ${{ github.sha }}.tar
#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: refs/heads/main
#     - uses: actions/download-artifact@v3
#       with:
#         name: docker@${{ github.sha }}
#     - env:
#         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#       run: |
#         ssh-agent -a $SSH_AUTH_SOCK > /dev/null
#         ssh-add - <<< "${{ secrets.ansible_ssh_key }}"
#     - env:
#         ANSIBLE_HOST_KEY_CHECKING: False
#         SSH_AUTH_SOCK: /tmp/ssh_agent.sock
#       run: |
#         ansible-galaxy collection install community.general
#         ansible-playbook --extra-vars="github_sha=${{ github.sha }} github_repository_name=${{ github.event.repository.name }}" --user=${{ secrets.ansible_user }} --inventory ${{ github.event.repository.name }}, deploy.yml
